services:
  - type: web
    name: portfolio-bloomberg-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_CHAT_ID
        sync: false
      - key: RENDER_URL
        sync: false
    healthCheckPath: /ping
    autoDeploy: true
